### ISSUE TITLE
Number of ecs does not match with jsonstream output

### ISSUE THREAD

**Issue by rsirres** [ezpaarse-project/node-ezpaarse#4]
I'm using ezpaarse 3.9.6 an the latest version of ezp.

I would expect that the number of expected ecs is independent from the output format.

However, if you run the bulk command with the "jsonstream" output you do not match the number of lines.
```
$ ezp bulk -h localhost:59599 -H 'Accept: application/jsonstream' -f test_ezp/ results/
[09:08:17] Info     Processing /tmp/test_ezp/ezproxy.log.20181117.log
[09:08:19] Error    File length (287 lines) does not match job report (288 ECs)
```

Running the command without output header the number of lines matches:

```
$ ezp bulk -h localhost:59599 -f test_ezp/ results/
[09:08:27] Info     Processing /tmp/test_ezp/ezproxy.log.20181117.log
```

Does the number of ecs in ezpaarse include the CSV header ?

**Comment by tporquet** [comment]
Currently, the ezp bulk command is "pre-wired" to work with CSV (with a header), in order to insert the results in ezMESURE. 
We'll soon adapt the ezp command so it's able to handle the ndjson format as well.
